# Generated by Django 4.2.30 on 2026-06-17 17:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField(help_text='The raw text entered by the user.', verbose_name='User Input')),
                ('category', models.CharField(choices=[('creative', 'Creative'), ('technical', 'Technical'), ('analytical', 'Analytical'), ('educational', 'Educational'), ('business', 'Business'), ('conversational', 'Conversational')], max_length=20, verbose_name='Detected Category')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
            ],
            options={
                'verbose_name': 'User Input',
                'verbose_name_plural': 'User Inputs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.TextField(verbose_name='Generated Prompt')),
                ('tone', models.CharField(choices=[('formal', 'Formal'), ('casual', 'Casual'), ('detailed', 'Detailed'), ('concise', 'Concise'), ('creative', 'Creative'), ('technical', 'Technical'), ('persuasive', 'Persuasive'), ('simple', 'Simple')], max_length=20, verbose_name='Detected Tone')),
                ('confidence_score', models.FloatField(help_text='Classifier confidence (0–1).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Confidence Score')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Generated At')),
                ('input_reference', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generated_prompt', to='generator.userinput', verbose_name='Source Input')),
            ],
            options={
                'verbose_name': 'Generated Prompt',
                'verbose_name_plural': 'Generated Prompts',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Rating (1–5)')),
                ('comment', models.TextField(blank=True, help_text='Optional written feedback.', verbose_name='Comment')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
                ('generated_prompt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='generator.generatedprompt', verbose_name='Generated Prompt')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
                'ordering': ['-timestamp'],
            },
        ),
    ]
